trigger:
- master


stages:
- stage: Compile
  displayName: Compile Sources
  jobs:
  - job: MVNWorker
    displayName: Worker
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'worker/pom.xml'
          goals: 'clean package'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          testRunTitle: 'Worker MVN'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.12'
          mavenVersionOption: 'Default'
          mavenOptions: '-Xmx3072m'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false

  - job: MVNPulser
    displayName: Pulser
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'worker/pom.xml'
          goals: 'clean package'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          testRunTitle: 'Pulser MVN'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.12'
          mavenVersionOption: 'Default'
          mavenOptions: '-Xmx3072m'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false

          
- stage: Dockerize
  displayName: Containerising with Docker
  dependsOn: Compile
  jobs:
  - job: DockerAPI
    displayName: Dockerize API Container
    steps:
    - task: Docker@2
      inputs:
        command: 'build'
        Dockerfile: 'api/dockerfile'
        buildContext: 'api/'
  - job: DockerDatabase
    displayName: Dockerize Database Container
    steps:
    - task: Docker@2
      inputs: 
       command: 'build'
       Dockerfile: '/database/Dockerfile'
       buildContext: '/database/'
  - job: DockerWorker
    displayName: Dockerizing Worker Container
    steps:
    - task: Docker@2
      inputs:
        command: 'build'
        Dockerfile: 'worker/dockerfile'
        buildContext: 'worker/'

  - job: DockerPulser
    displayName: Dockerizing Pulser Container
    steps:
    - task: Docker@2
      inputs:
        command: 'build'
        Dockerfile: 'pulser/dockerfile'
        buildContext: 'pulser/'

        
- stage: Smokes
  dependsOn: Dockerize
  displayName: Smoke Testing Items
  jobs:
  - job: startDB
  - job: dockerCompose