trigger:
- master


stages:
- stage: Compile
  displayName: Compile Sources
  jobs:
  - job: A1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - bash: echo "I´m alive"
  - job: A2

- stage: Dockerize
  displayName: Containerising with Docker
  dependsOn: Compile
  jobs:
  - job: B1
  - job: B2

- stage: Smoke Tests
  dependsOn: Dockerize
  displayName: Smoke Testing Items
  jobs:
  - job: startDB
  - job: dockerCompose