name: Java CI - Pulser

on: 
  pull_request:
    paths:
      - 'pulser/*'
      - 'core/*'
    branches: 
      - master
      - dev'


jobs:
  buildWithMaven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build with Maven  
      run: mvn package verify --file pulser/pom.xml

  BuildWithDocker:
    runs-on: ubuntu-latest
    steps:  
      - uses: whoan/docker-build-with-cache-action@v1
        name: Build Pulser in Docker
        with:
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          image_name: microtope/pulser
          image_tag: latest
          registry: docker.pkg.github.com
          context: ./pulser
          dockerfile: BuildDockerfile
          push_image_and_stages: false 
