name: Build DB Docker Image

on: 
  pull_request:
    paths:
      - 'database/*'
    branches: 
      - master
      - dev

jobs:
  buildDB:
    runs-on: ubuntu-latest
    steps:  
      - uses: whoan/docker-build-with-cache-action@v1
        name: Build DB in Docker
        with:
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          image_name: microtope/database
          image_tag: latest
          registry: docker.pkg.github.com
          context: ./database
          dockerfile: Dockerfile
          push_image_and_stages: false 