name: Java CI - Worker

on: 
  pull_request:
    paths:
      - 'worker/*'
    branches: 
      - master
      - dev

jobs:
  buildFromMaven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build with Maven  
      run: mvn package verify --file worker/pom.xml

  buildFromDocker:
    runs-on: ubuntu-latest
    steps:  
      - uses: whoan/docker-build-with-cache-action@v1
        name: Build Worker in Docker
        with:
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          image_name: microtope/worker
          image_tag: latest
          registry: docker.pkg.github.com
          context: ./worker
          dockerfile: BuildDockerfile
          push_image_and_stages: false 