name: API CI Action on PR

on: 
  pull_request:
    paths:
      - 'api/*'

jobs:
  BuildWithDocker:
    runs-on: ubuntu-latest
    steps:  
      - uses: whoan/docker-build-with-cache-action@v1
        name: Build in Docker
        with:
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          image_name: microtope/api
          image_tag: latest
          context: ./api
          dockerfile: Dockerfile
          push_image_and_stages: false 

