on: 
  pull_request:
    paths:
      - 'ui/*'
    branches: 
      - master
      - dev

name: Build UI in Docker

jobs:
  BuildWithDocker:
    runs-on: ubuntu-latest
    steps:  
      - uses: whoan/docker-build-with-cache-action@v1
        name: Build UI in Docker
        with:
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          image_name: microtope/ui
          image_tag: latest
          registry: docker.pkg.github.com
          context: ./ui
          dockerfile: Dockerfile
          push_image_and_stages: false 
