name: Java CI - Worker

on: 
  pull_request:
    paths:
      - 'worker/*'

jobs:
  buildFromMaven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build with Maven  
      run: mvn package verify --file worker/pom.xml

  buildFromDocker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build Worker From Docker
      uses: actions/docker/cli@master
      with:
        args: build -f /worker/BuildDockerfile ./worker
