name: BuildEverything

on:
  schedule:
  - cron: "0 0 * * *"
  - cron: "0 12 * * *"

jobs:

  buildCoreAsMavenJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build with Maven  
      run: mvn package verify --file core/pom.xml


  buildPulserAsMavenJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build Core Library
      run: mvn install package verify --file core/pom.xml
    - name: Build Pulser with Maven  
      run: mvn package verify --file pulser/pom.xml

  buildWorkerAsMavenJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build Core Library
      run: mvn install package verify --file core/pom.xml
    - name: Build Worker with Maven  
      run: mvn package verify --file worker/pom.xml

  BuildAPIWithDocker:
    runs-on: ubuntu-latest
    steps:  
      - uses: whoan/docker-build-with-cache-action@v1
        name: Build API in Docker
        with:
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          image_name: microtope/api
          image_tag: latest
          registry: docker.pkg.github.com
          context: ./api
          dockerfile: Dockerfile
          push_image_and_stages: false 

  buildDBWithDocker:
    runs-on: ubuntu-latest
    steps:  
      - uses: whoan/docker-build-with-cache-action@v1
        name: Build DB in Docker
        with:
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          image_name: microtope/database
          image_tag: latest
          registry: docker.pkg.github.com
          context: ./database
          dockerfile: Dockerfile
          push_image_and_stages: false 

  buildPulserFromDocker:
    runs-on: ubuntu-latest
    steps:  
      - uses: whoan/docker-build-with-cache-action@v1
        name: Build Pulser in Docker
        with:
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          image_name: microtope/pulser
          image_tag: latest
          registry: docker.pkg.github.com
          context: ./pulser
          dockerfile: BuildDockerfile
          push_image_and_stages: false 

  BuildUIWithDocker:
    runs-on: ubuntu-latest
    steps:  
      - uses: whoan/docker-build-with-cache-action@v1
        name: Build UI in Docker
        with:
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          image_name: microtope/ui
          image_tag: latest
          registry: docker.pkg.github.com
          context: ./ui
          dockerfile: Dockerfile
          push_image_and_stages: false 

  buildWorkerFromDocker:
    runs-on: ubuntu-latest
    steps:  
      - uses: whoan/docker-build-with-cache-action@v1
        name: Build Worker in Docker
        with:
          username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          image_name: microtope/worker
          image_tag: latest
          registry: docker.pkg.github.com
          context: ./worker
          dockerfile: BuildDockerfile
          push_image_and_stages: false 