name: Auto merge Dependabot updates

on:
  check_suite:
    types:
      - completed

jobs:
  merge-me:
    name: Dependabot merge
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot merge
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
