name: Automatic Housekeeping

on:
  check_suite:
    types:
      - completed
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Thank you for Contributing! Take the time until I check your appreciated Pull Request to see if any labels are missing and watch the pipeline :) '

  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
     
  merge-me:
    name: Dependabot merge
    runs-on: ubuntu-latest
    needs:
          - label
          - greet
    steps:
      - name: Sleep for 180 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '180s'

      - name: Dependabot merge
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
